### ISSUE TITLE
MultiConnect GUI

### ISSUE THREAD

**Issue by ZeroPointNothing** [ZeroPointNothing/MultiConnnect#3]
Currently, anyone trying to connect to the host Computer will have to do it through a web browser, which might be a little confusing and doesn't look as good.

To solve this issue, an interactive GUI can be made. However, it needs to have the following:

- [x] Input fields
- [x] Output fields
- [x] Image display fields
- [x] The ability to initiate downloads from `/dwlfile`
- [x] Connection status field

**Comment by zeropointnothing** [comment]
Images, along with certain files accessed from /disfile have to be opened through the browser, as the customtkinter does not have a simple solution to having images that won't cause issues later on. As of now, all files that raise an error will be attempted to be opened inside the user's browser.

Connection status field, while not actually implemented, is replaced with the user getting responses back. A try/except block is in place for when the machine stops accepting inputs, aka: MultiConnect is offline for it.
